name: Deploy scraper (only /server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only --config server/fly.toml --path server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

